### ISSUE TITLE
watson module has no attribute ''register"

### ISSUE THREAD

**Issue by j1fig** [etianen/django-watson#143]
Hi,

After upgrading to 1.2.0. the following error pops up:

    File "/home/xxxxx/projects/yyyyy/djangoproject/core/apps.py", line 12, in ready
        watson.register(User)
    AttributeError: 'module' object has no attribute 'register'

Tried with 1.1.8 and everything is working fine.

Check if you can replicate the issue, otherwise I can provide some more info on my environment.

**Comment by etianen** [comment]
Please check the release notes:

https://github.com/etianen/django-watson/blob/master/CHANGELOG.markdown

**Comment by j1fig** [comment]
My bad ;) thanks @etianen
